[project]
name = "trakka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-extensions>=4.1",
    "django-widget-tweaks>=1.5.1",
    "python-decouple>=3.8",
]
